"""Add user model and campaign tenancy ownership

Revision ID: 0367588b6490
Revises: 3cd76ac4dfdb
Create Date: 2026-07-06 16:28:16.619919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0367588b6490'
down_revision: Union[str, Sequence[str], None] = '3cd76ac4dfdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    
    # --- MANUAL ADJUSTMENT: Clear legacy data before adding NOT NULL constraint ---
    op.execute("DELETE FROM match_results;")
    op.execute("DELETE FROM campaigns;")
    # ------------------------------------------------------------------------------
    
    op.add_column('campaigns', sa.Column('owner_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'campaigns', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.drop_column('campaigns', 'owner_id')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###