"""add_influencer_metric_logs

Revision ID: 3cd76ac4dfdb
Revises: de5d6d77334a
Create Date: 2026-06-27 02:02:39.086784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cd76ac4dfdb'
down_revision: Union[str, Sequence[str], None] = 'de5d6d77334a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
