"""Initial V3 Build

Revision ID: 5351f198095d
Revises: 
Create Date: 2026-06-25 05:27:19.324435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5351f198095d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('niche', sa.String(length=200), nullable=False),
    sa.Column('audience', sa.String(length=500), nullable=False),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('target_reach', sa.Integer(), nullable=False),
    sa.Column('brief_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('influencers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('profile_url', sa.String(length=500), nullable=True),
    sa.Column('follower_count', sa.Integer(), nullable=False),
    sa.Column('following_count', sa.Integer(), nullable=False),
    sa.Column('total_likes', sa.BigInteger(), nullable=False),
    sa.Column('total_comments', sa.BigInteger(), nullable=False),
    sa.Column('avg_views', sa.Integer(), nullable=True),
    sa.Column('post_count', sa.Integer(), nullable=False),
    sa.Column('estimated_cpe', sa.Float(), nullable=True),
    sa.Column('price_per_post', sa.Float(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('recent_posts', sa.Text(), nullable=True),
    sa.Column('niche_tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('engagement_rate', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_influencers_username'), 'influencers', ['username'], unique=True)
    op.create_table('match_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('influencer_id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('semantic_score', sa.Float(), nullable=True),
    sa.Column('authenticity_score', sa.Float(), nullable=True),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('cpe', sa.Float(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_results')
    op.drop_index(op.f('ix_influencers_username'), table_name='influencers')
    op.drop_table('influencers')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
