"""add_influencer_metric_logs

Revision ID: 5da1d4ba1010
Revises: 5351f198095d
Create Date: 2026-06-26 04:12:33.899235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5da1d4ba1010'
down_revision: Union[str, Sequence[str], None] = '5351f198095d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('influencer_metric_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('influencer_id', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('follower_count', sa.Integer(), nullable=False),
    sa.Column('avg_views', sa.Integer(), nullable=True),
    sa.Column('est_cpe', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('influencer_metric_logs')
    # ### end Alembic commands ###
