"""merge AI tracking columns into postgres

Revision ID: 6c4ff2980c98
Revises: 1adcf749b90a
Create Date: 2026-06-23 03:05:20.472212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c4ff2980c98'
down_revision: Union[str, None] = '1adcf749b90a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('brief_text', sa.Text(), nullable=True))
    op.alter_column('campaigns', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('influencers', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('influencers', 'follower_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('influencers', 'following_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('influencers', 'total_likes',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('influencers', 'total_comments',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('influencers', 'post_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('influencers', 'niche_tags',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('influencers', 'source',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('influencers', 'scraped_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('influencers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('match_results', sa.Column('semantic_score', sa.Float(), nullable=True))
    op.add_column('match_results', sa.Column('authenticity_score', sa.Float(), nullable=True))
    op.add_column('match_results', sa.Column('cpe', sa.Float(), nullable=True))
    op.add_column('match_results', sa.Column('explanation', sa.Text(), nullable=True))
    op.add_column('match_results', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_results', 'created_at')
    op.drop_column('match_results', 'explanation')
    op.drop_column('match_results', 'cpe')
    op.drop_column('match_results', 'authenticity_score')
    op.drop_column('match_results', 'semantic_score')
    op.alter_column('influencers', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('influencers', 'scraped_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('influencers', 'source',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('influencers', 'niche_tags',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
    op.alter_column('influencers', 'post_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('influencers', 'total_comments',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('influencers', 'total_likes',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('influencers', 'following_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('influencers', 'follower_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('influencers', 'updated_at')
    op.alter_column('campaigns', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('campaigns', 'brief_text')
    # ### end Alembic commands ###
