"""add user profile fields

Revision ID: b6ea8ede11c7
Revises: 0367588b6490
Create Date: 2026-08-04 01:57:51.178276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6ea8ede11c7'
down_revision: Union[str, Sequence[str], None] = '0367588b6490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(length=150), nullable=True))
    op.add_column('users', sa.Column('company_or_agency', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'company_or_agency')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
