"""create tables

Revision ID: b7d721797579
Revises: 
Create Date: 2026-06-23 01:49:24.556050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7d721797579'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('niche', sa.String(), nullable=False),
    sa.Column('audience', sa.String(), nullable=False),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('target_reach', sa.Integer(), nullable=False),
    sa.Column('brief_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('influencers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('profile_url', sa.String(), nullable=True),
    sa.Column('follower_count', sa.Integer(), nullable=True),
    sa.Column('following_count', sa.Integer(), nullable=True),
    sa.Column('total_likes', sa.BigInteger(), nullable=True),
    sa.Column('total_comments', sa.BigInteger(), nullable=True),
    sa.Column('avg_views', sa.Integer(), nullable=True),
    sa.Column('post_count', sa.Integer(), nullable=True),
    sa.Column('estimated_cpe', sa.Float(), nullable=True),
    sa.Column('price_per_post', sa.Float(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('recent_posts', sa.Text(), nullable=True),
    sa.Column('niche_tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('engagement_rate', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_influencers_username'), 'influencers', ['username'], unique=True)
    op.create_table('match_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('influencer_id', sa.UUID(), nullable=False),
    sa.Column('semantic_score', sa.Float(), nullable=False),
    sa.Column('authenticity_score', sa.Float(), nullable=False),
    sa.Column('fit_score', sa.Float(), nullable=False),
    sa.Column('cpe', sa.Float(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_results')
    op.drop_index(op.f('ix_influencers_username'), table_name='influencers')
    op.drop_table('influencers')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
