"""Initial V3 schema

Revision ID: ecf66bb71b9e
Revises: 
Create Date: 2026-06-25 02:28:35.714076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ecf66bb71b9e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campaigns', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('influencers', 'follower_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('influencers', 'following_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('influencers', 'total_likes',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('influencers', 'total_comments',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('influencers', 'post_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('influencers', 'source',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('influencers', 'scraped_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('influencers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('influencers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('match_results', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('match_results', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('influencers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('influencers', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('influencers', 'scraped_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('influencers', 'source',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('influencers', 'post_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('influencers', 'total_comments',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('influencers', 'total_likes',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('influencers', 'following_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('influencers', 'follower_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('campaigns', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
